# See https://github.com/actions/runner-images/tree/main/images/macos
# to update configuration when GitHub breaks it

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-26

    strategy:
      matrix:
        xcodebuild-destination: ['platform=iOS Simulator,name=iPhone 17', 'platform=macOS']
        xcodebuild-command: ['build', 'test']

    steps:
    - uses: actions/checkout@v3
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.2.0.app
    - name: Build and run tests for the matrix
      run: xcodebuild ${{ matrix.xcodebuild-command }} -scheme NautilusTelemetry-Package -destination "${{ matrix.xcodebuild-destination }}"

